import type { RawDay } from './curriculum-data';
import { w } from './curriculum-data-helpers';

export const CURRICULUM_PART4: RawDay[] = [
  {
    day: 16,
    theme: 'Clothing & shopping',
    grammarFocus: 'Accusative animate/inanimate',
    words: [
      w('одежда', 'clothes', 'Новая одежда.', 'New clothes.', 'Магазин одежды.', 'Clothing store.'),
      w('рубашка', 'shirt', 'Белая рубашка.', 'A white shirt.', 'Купи рубашку.', 'Buy a shirt.'),
      w('платье', 'dress', 'Красивое платье.', 'A beautiful dress.', 'Она в платье.', 'She is in a dress.'),
      w('брюки', 'pants / trousers', 'Чёрные брюки.', 'Black pants.', 'Новые брюки.', 'New pants.'),
      w('обувь', 'footwear / shoes', 'Удобная обувь.', 'Comfortable shoes.', 'Магазин обуви.', 'Shoe store.'),
      w('размер', 'size', 'Какой размер?', 'What size?', 'Мой размер — средний.', 'My size is medium.'),
      w('цена', 'price', 'Какая цена?', 'What is the price?', 'Цена высокая.', 'The price is high.'),
      w('скидка', 'discount', 'Большая скидка.', 'A big discount.', 'Скидка пятьдесят процентов.', 'Fifty percent discount.'),
      w('примерить', 'to try on', 'Можно примерить?', 'Can I try it on?', 'Примерьте это.', 'Try this on.'),
      w('купить', 'to buy', 'Хочу купить.', 'I want to buy.', 'Купи хлеб.', 'Buy bread.'),
    ],
    grammarPrompts: [
      { prompt: 'Я вижу ___ (friend, animate acc)', options: ['друг', 'друга', 'другу', 'другом'], correct: 1 },
      { prompt: 'Я читаю ___ (book)', options: ['книга', 'книгу', 'книги', 'книге'], correct: 1 },
      { prompt: 'Я знаю ___ (doctor, animate)', options: ['врач', 'врача', 'врачу', 'врачом'], correct: 1 },
      { prompt: 'Покупаю ___ (dress)', options: ['платье', 'платья', 'платью', 'платьем'], correct: 0 },
      { prompt: 'Вижу ___ (cat, animate)', options: ['кошка', 'кошку', 'кошки', 'кошке'], correct: 1 },
      { prompt: 'Ношу ___ (shirt)', options: ['рубашка', 'рубашку', 'рубашки', 'рубашке'], correct: 1 },
    ],
    speakingPrompts: ['Какой размер?', 'Можно примерить?', 'Какая цена?', 'Большая скидка.', 'Хочу купить рубашку.'],
  },
  {
    day: 17,
    theme: 'Work & professions',
    grammarFocus: 'Instrumental (быть + profession)',
    words: [
      w('работа', 'work / job', 'Я на работе.', 'I am at work.', 'Работа интересная.', 'The job is interesting.'),
      w('офис', 'office', 'Офис в центре.', 'The office is downtown.', 'Иду в офис.', 'I am going to the office.'),
      w('учитель', 'teacher', 'Она учитель.', 'She is a teacher.', 'Хороший учитель.', 'A good teacher.'),
      w('инженер', 'engineer', 'Он инженер.', 'He is an engineer.', 'Инженер работает.', 'The engineer works.'),
      w('врач', 'doctor', 'Моя сестра врач.', 'My sister is a doctor.', 'Врач в больнице.', 'The doctor is at the hospital.'),
      w('студент', 'student', 'Я студент.', 'I am a student.', 'Студенты учатся.', 'Students study.'),
      w('начальник', 'boss / manager', 'Начальник строгий.', 'The boss is strict.', 'Мой начальник.', 'My boss.'),
      w('зарплата', 'salary', 'Зарплата хорошая.', 'The salary is good.', 'Когда зарплата?', 'When is payday?'),
      w('коллега', 'colleague', 'Мой коллега.', 'My colleague.', 'Коллеги помогают.', 'Colleagues help.'),
      w('карьера', 'career', 'Карьера важна.', 'Career is important.', 'Успешная карьера.', 'A successful career.'),
    ],
    grammarPrompts: [
      { prompt: 'Она работает ___. (as teacher, inst)', options: ['учитель', 'учителем', 'учителя', 'учителю'], correct: 1 },
      { prompt: 'Он был ___. (engineer, inst)', options: ['инженер', 'инженером', 'инженера', 'инженеру'], correct: 1 },
      { prompt: 'Стать ___. (doctor, inst)', options: ['врач', 'врачом', 'врача', 'врачу'], correct: 1 },
      { prompt: 'Мечтаю быть ___. (student, inst)', options: ['студент', 'студентом', 'студента', 'студенту'], correct: 1 },
      { prompt: 'Горжусь ___. (colleague, inst)', options: ['коллега', 'коллегой', 'коллегу', 'коллеге'], correct: 1 },
      { prompt: 'Стал ___. (boss, inst)', options: ['начальник', 'начальником', 'начальника', 'начальнику'], correct: 1 },
    ],
    speakingPrompts: ['Я на работе.', 'Она учитель.', 'Мой коллега помогает.', 'Офис в центре.', 'Карьера важна.'],
  },
  {
    day: 18,
    theme: 'Hobbies & free time',
    grammarFocus: 'Verb aspect intro (perfective/imperfective)',
    words: [
      w('хобби', 'hobby', 'Моё хобби — музыка.', 'My hobby is music.', 'Какое у тебя хобби?', 'What is your hobby?'),
      w('музыка', 'music', 'Я люблю музыку.', 'I love music.', 'Громкая музыка.', 'Loud music.'),
      w('кино', 'cinema / movies', 'Идём в кино.', 'Let\'s go to the movies.', 'Хорошее кино.', 'A good movie.'),
      w('книга', 'book', 'Интересная книга.', 'An interesting book.', 'Читаю книгу.', 'I am reading a book.'),
      w('спорт', 'sport', 'Занимаюсь спортом.', 'I do sports.', 'Спорт полезен.', 'Sport is healthy.'),
      w('игра', 'game', 'Играем в игру.', 'We play a game.', 'Интересная игра.', 'An interesting game.'),
      w('рисовать', 'to draw', 'Люблю рисовать.', 'I like to draw.', 'Рисую картину.', 'I am drawing a picture.'),
      w('читать', 'to read', 'Читаю каждый день.', 'I read every day.', 'Читай книгу.', 'Read the book.'),
      w('слушать', 'to listen', 'Слушаю музыку.', 'I listen to music.', 'Слушай внимательно.', 'Listen carefully.'),
      w('смотреть', 'to watch / look', 'Смотрю кино.', 'I watch movies.', 'Смотри на меня.', 'Look at me.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ книгу. (read, process/imperf)', options: ['прочитаю', 'читаю', 'прочитал', 'прочитала'], correct: 1 },
      { prompt: 'Я ___ фильм. (watch, process)', options: ['посмотрю', 'смотрю', 'посмотрел', 'посмотрела'], correct: 1 },
      { prompt: 'Завтра ___ письмо. (write, completed)', options: ['пишу', 'напишу', 'писал', 'писала'], correct: 1 },
      { prompt: 'Каждый день ___ спортом. (do)', options: ['занимаюсь', 'займусь', 'занимался', 'занималась'], correct: 0 },
      { prompt: 'Сейчас ___ музыку. (listen)', options: ['послушаю', 'слушаю', 'слушал', 'слушала'], correct: 1 },
      { prompt: 'Вчера ___ картину. (draw, completed)', options: ['рисую', 'нарисую', 'нарисовал', 'рисовал'], correct: 2 },
    ],
    speakingPrompts: ['Моё хобби — музыка.', 'Идём в кино.', 'Читаю каждый день.', 'Слушаю музыку.', 'Люблю рисовать.'],
  },
  {
    day: 19,
    theme: 'Sports & movement',
    grammarFocus: 'Verbs of motion (unidirectional)',
    words: [
      w('футбол', 'football / soccer', 'Играем в футбол.', 'We play football.', 'Люблю футбол.', 'I love football.'),
      w('бег', 'running', 'Бег полезен.', 'Running is healthy.', 'Утренний бег.', 'Morning run.'),
      w('плавание', 'swimming', 'Плавание — мой спорт.', 'Swimming is my sport.', 'Занимаюсь плаванием.', 'I do swimming.'),
      w('тренировка', 'training / workout', 'Тренировка в шесть.', 'Training at six.', 'Тяжёлая тренировка.', 'Hard workout.'),
      w('команда', 'team', 'Наша команда выиграла.', 'Our team won.', 'Сильная команда.', 'Strong team.'),
      w('победа', 'victory / win', 'Победа важна.', 'Victory is important.', 'Сладкая победа.', 'Sweet victory.'),
      w('бегать', 'to run (multi-dir)', 'Бегаю каждый день.', 'I run every day.', 'Дети бегают.', 'Children run.'),
      w('плавать', 'to swim', 'Плаваю в бассейне.', 'I swim in the pool.', 'Умею плавать.', 'I can swim.'),
      w('прыгать', 'to jump', 'Прыгаю высоко.', 'I jump high.', 'Кошка прыгает.', 'The cat jumps.'),
      w('победить', 'to win / defeat', 'Мы победили!', 'We won!', 'Хочу победить.', 'I want to win.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ в парк. (go on foot, one way)', options: ['иду', 'хожу', 'ехал', 'езжу'], correct: 0 },
      { prompt: 'Каждый день ___ в школу. (go habitually)', options: ['иду', 'хожу', 'шёл', 'шла'], correct: 1 },
      { prompt: 'Сейчас ___ на автобусе. (ride, one way)', options: ['еду', 'езжу', 'ехал', 'ехала'], correct: 0 },
      { prompt: 'Он ___ в бассейн. (swim, one way)', options: ['плывёт', 'плавает', 'плыл', 'плавала'], correct: 0 },
      { prompt: 'Мы ___ домой. (carry, one way)', options: ['несём', 'носим', 'несли', 'носила'], correct: 0 },
      { prompt: 'Летом часто ___ на море. (go habitually)', options: ['еду', 'езжу', 'ехал', 'ехала'], correct: 1 },
    ],
    speakingPrompts: ['Играем в футбол.', 'Бегаю каждый день.', 'Наша команда выиграла.', 'Плаваю в бассейне.', 'Мы победили!'],
  },
  {
    day: 20,
    theme: 'Nature & outdoors',
    grammarFocus: 'Genitive plural (some patterns)',
    words: [
      w('лес', 'forest', 'Гуляем в лесу.', 'We walk in the forest.', 'Тёмный лес.', 'Dark forest.'),
      w('река', 'river', 'Река широкая.', 'The river is wide.', 'Большая река.', 'A big river.'),
      w('гора', 'mountain', 'Высокая гора.', 'A high mountain.', 'В горах холодно.', 'It is cold in the mountains.'),
      w('море', 'sea', 'Море синее.', 'The sea is blue.', 'Летом на море.', 'At the sea in summer.'),
      w('озеро', 'lake', 'Озеро глубокое.', 'The lake is deep.', 'У озера дом.', 'A house by the lake.'),
      w('дерево', 'tree', 'Высокое дерево.', 'A tall tree.', 'Много деревьев.', 'Many trees.'),
      w('цветок', 'flower', 'Красивый цветок.', 'A beautiful flower.', 'Букет цветов.', 'A bouquet of flowers.'),
      w('природа', 'nature', 'Люблю природу.', 'I love nature.', 'Красивая природа.', 'Beautiful nature.'),
      w('воздух', 'air', 'Свежий воздух.', 'Fresh air.', 'Чистый воздух.', 'Clean air.'),
      w('остров', 'island', 'Остров в море.', 'An island in the sea.', 'Тропический остров.', 'A tropical island.'),
    ],
    grammarPrompts: [
      { prompt: 'много ___ (tree, gen pl)', options: ['дерево', 'дерева', 'деревьев', 'деревья'], correct: 2 },
      { prompt: 'нет ___ (flower, gen pl)', options: ['цветы', 'цветов', 'цветам', 'цветами'], correct: 1 },
      { prompt: 'мало ___ (book, gen pl)', options: ['книги', 'книг', 'книгам', 'книгами'], correct: 1 },
      { prompt: 'сколько ___ (friend, gen pl)', options: ['друзья', 'друзей', 'друзьям', 'друзьями'], correct: 1 },
      { prompt: 'нет ___ (apple, gen pl)', options: ['яблоки', 'яблок', 'яблокам', 'яблоками'], correct: 1 },
      { prompt: 'много ___ (child, gen pl)', options: ['дети', 'детей', 'детям', 'детьми'], correct: 1 },
    ],
    speakingPrompts: ['Гуляем в лесу.', 'Море синее.', 'Свежий воздух.', 'Люблю природу.', 'Высокая гора.'],
  },
];
