import type { RawDay } from './curriculum-data';
import { w } from './curriculum-data-helpers';

export const CURRICULUM_PART3: RawDay[] = [
  {
    day: 11,
    theme: 'Directions & transport',
    grammarFocus: 'Motion verbs (идти/ехать intro)',
    words: [
      w('метро', 'metro / subway', 'Еду на метро.', 'I take the metro.', 'Станция метро там.', 'The metro station is there.'),
      w('автобус', 'bus', 'Автобус опаздывает.', 'The bus is late.', 'Садись в автобус.', 'Get on the bus.'),
      w('поезд', 'train', 'Поезд отправляется в шесть.', 'The train departs at six.', 'Еду на поезде.', 'I travel by train.'),
      w('такси', 'taxi', 'Вызови такси.', 'Call a taxi.', 'Такси ждёт нас.', 'The taxi is waiting for us.'),
      w('направо', 'to the right', 'Поверни направо.', 'Turn right.', 'Банк направо.', 'The bank is on the right.'),
      w('налево', 'to the left', 'Иди налево.', 'Go left.', 'Магазин налево.', 'The store is on the left.'),
      w('прямо', 'straight ahead', 'Идите прямо.', 'Go straight.', 'Прямо двести метров.', 'Straight for two hundred meters.'),
      w('рядом', 'nearby', 'Аптека рядом.', 'The pharmacy is nearby.', 'Живу рядом с парком.', 'I live near the park.'),
      w('далеко', 'far', 'Станция далеко.', 'The station is far.', 'Далеко идти.', 'It is far to walk.'),
      w('карта', 'map', 'Посмотри на карту.', 'Look at the map.', 'Карта города.', 'A map of the city.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ пешком. (go on foot)', options: ['иду', 'еду', 'лежу', 'стою'], correct: 0 },
      { prompt: 'Она ___ на автобусе. (go by transport)', options: ['идёт', 'едет', 'бежит', 'летит'], correct: 1 },
      { prompt: 'Мы ___ в Москву. (go by train)', options: ['идём', 'едем', 'плывём', 'бежим'], correct: 1 },
      { prompt: 'Куда ты ___? (going)', options: ['идёшь', 'едешь', 'both ok', 'спишь'], correct: 2 },
      { prompt: 'Дети ___ в школу. (walk)', options: ['идут', 'едут', 'летят', 'плывут'], correct: 0 },
      { prompt: 'Он ___ на метро. (rides)', options: ['идёт', 'едет', 'бежит', 'стоит'], correct: 1 },
    ],
    speakingPrompts: ['Поверни направо.', 'Станция метро там.', 'Идите прямо.', 'Аптека рядом.', 'Еду на поезде.'],
  },
  {
    day: 12,
    theme: 'Time & schedules',
    grammarFocus: 'Time expressions, когда/в',
    words: [
      w('час', 'hour / o\'clock', 'Сейчас три часа.', 'It is three o\'clock now.', 'Час назад.', 'An hour ago.'),
      w('минута', 'minute', 'Подожди минуту.', 'Wait a minute.', 'Пять минут до автобуса.', 'Five minutes until the bus.'),
      w('утро', 'morning', 'Утром пью кофе.', 'I drink coffee in the morning.', 'Доброе утро!', 'Good morning!'),
      w('день', 'day / afternoon', 'Хорошего дня!', 'Have a good day!', 'Днём работаю.', 'I work during the day.'),
      w('вечер', 'evening', 'Добрый вечер!', 'Good evening!', 'Вечером отдыхаю.', 'I rest in the evening.'),
      w('ночь', 'night', 'Спокойной ночи!', 'Good night!', 'Ночью тихо.', 'It is quiet at night.'),
      w('сегодня', 'today', 'Сегодня понедельник.', 'Today is Monday.', 'Сегодня холодно.', 'It is cold today.'),
      w('завтра', 'tomorrow', 'Увидимся завтра.', 'See you tomorrow.', 'Завтра экзамен.', 'The exam is tomorrow.'),
      w('вчера', 'yesterday', 'Вчера был дождь.', 'It rained yesterday.', 'Вчера я работал.', 'I worked yesterday.'),
      w('когда', 'when', 'Когда ты приедешь?', 'When will you arrive?', 'Когда начинается?', 'When does it start?'),
    ],
    grammarPrompts: [
      { prompt: 'Встреча ___ три часа. (at)', options: ['в', 'на', 'к', 'из'], correct: 0 },
      { prompt: '___ утро пью чай. (in the)', options: ['В', 'На', 'К', 'Из'], correct: 0 },
      { prompt: '___ понедельник работаю. (on)', options: ['В', 'На', 'К', 'Из'], correct: 0 },
      { prompt: '___ котором часу? (at what time)', options: ['В', 'На', 'К', 'Из'], correct: 0 },
      { prompt: '___ вечер иду домой. (in the)', options: ['В', 'На', 'К', 'Из'], correct: 0 },
      { prompt: '___ сколько? (until when)', options: ['До', 'В', 'На', 'К'], correct: 0 },
    ],
    speakingPrompts: ['Сейчас три часа.', 'Доброе утро!', 'Увидимся завтра.', 'Когда ты приедешь?', 'Вечером отдыхаю.'],
  },
  {
    day: 13,
    theme: 'Days, months, seasons',
    grammarFocus: 'Genitive singular (dates)',
    words: [
      w('понедельник', 'Monday', 'В понедельник работаю.', 'I work on Monday.', 'Следующий понедельник.', 'Next Monday.'),
      w('январь', 'January', 'Январь — холодный месяц.', 'January is a cold month.', 'В январе снег.', 'There is snow in January.'),
      w('зима', 'winter', 'Зимой холодно.', 'It is cold in winter.', 'Зима длинная.', 'Winter is long.'),
      w('весна', 'spring', 'Весной тепло.', 'It is warm in spring.', 'Весна красивая.', 'Spring is beautiful.'),
      w('лето', 'summer', 'Летом еду на море.', 'In summer I go to the sea.', 'Лето короткое.', 'Summer is short.'),
      w('осень', 'autumn / fall', 'Осенью дождь.', 'It rains in autumn.', 'Осень золотая.', 'Autumn is golden.'),
      w('неделя', 'week', 'На следующей неделе.', 'Next week.', 'Неделя пролетела.', 'The week flew by.'),
      w('месяц', 'month', 'Месяц назад.', 'A month ago.', 'Каждый месяц.', 'Every month.'),
      w('дата', 'date', 'Какая сегодня дата?', 'What is the date today?', 'Дата рождения.', 'Date of birth.'),
      w('праздник', 'holiday', 'Сегодня праздник.', 'Today is a holiday.', 'С Новым годом!', 'Happy New Year!'),
    ],
    grammarPrompts: [
      { prompt: 'первое ___ (January, gen)', options: ['январь', 'января', 'январе', 'январём'], correct: 1 },
      { prompt: 'второе ___ (March, gen)', options: ['март', 'марта', 'марте', 'мартом'], correct: 1 },
      { prompt: '___ года (of the year)', options: ['год', 'года', 'году', 'годом'], correct: 1 },
      { prompt: 'начало ___ (week, gen)', options: ['неделя', 'недели', 'неделе', 'неделю'], correct: 1 },
      { prompt: 'середина ___ (month, gen)', options: ['месяц', 'месяца', 'месяце', 'месяцем'], correct: 1 },
      { prompt: 'конец ___ (winter, gen)', options: ['зима', 'зимы', 'зиме', 'зимой'], correct: 1 },
    ],
    speakingPrompts: ['Сегодня понедельник.', 'Зимой холодно.', 'Какая сегодня дата?', 'С Новым годом!', 'На следующей неделе.'],
  },
  {
    day: 14,
    theme: 'Weather',
    grammarFocus: 'Impersonal constructions (холодно)',
    words: [
      w('погода', 'weather', 'Погода хорошая.', 'The weather is good.', 'Какая погода?', 'What is the weather like?'),
      w('дождь', 'rain', 'Идёт дождь.', 'It is raining.', 'Дождь весь день.', 'Rain all day.'),
      w('снег', 'snow', 'Идёт снег.', 'It is snowing.', 'Белый снег.', 'White snow.'),
      w('солнце', 'sun', 'Солнце светит.', 'The sun is shining.', 'Яркое солнце.', 'Bright sun.'),
      w('ветер', 'wind', 'Сильный ветер.', 'Strong wind.', 'Ветер холодный.', 'The wind is cold.'),
      w('жарко', 'hot (weather)', 'Сегодня жарко.', 'It is hot today.', 'Летом жарко.', 'It is hot in summer.'),
      w('холодно', 'cold (weather)', 'Зимой холодно.', 'It is cold in winter.', 'Мне холодно.', 'I am cold.'),
      w('тепло', 'warm (weather)', 'Весной тепло.', 'It is warm in spring.', 'Сегодня тепло.', 'It is warm today.'),
      w('облако', 'cloud', 'На небе облака.', 'Clouds in the sky.', 'Серые облака.', 'Gray clouds.'),
      w('градус', 'degree', 'Минус десять градусов.', 'Minus ten degrees.', 'Сколько градусов?', 'How many degrees?'),
    ],
    grammarPrompts: [
      { prompt: 'Сегодня ___. (it is cold)', options: ['холодный', 'холодно', 'холодная', 'холодные'], correct: 1 },
      { prompt: 'Летом ___. (it is hot)', options: ['жаркий', 'жарко', 'жаркая', 'жаркие'], correct: 1 },
      { prompt: '___ идёт дождь. (outside)', options: ['На', 'На улице', 'В', 'К'], correct: 1 },
      { prompt: 'Мне ___. (I am cold)', options: ['холодный', 'холодно', 'холодная', 'холоден'], correct: 1 },
      { prompt: 'На улице ___. (windy)', options: ['ветер', 'ветрено', 'ветреный', 'ветреная'], correct: 1 },
      { prompt: 'Сейчас ___. (it is warm)', options: ['теплый', 'тепло', 'тёплая', 'тёплые'], correct: 1 },
    ],
    speakingPrompts: ['Сегодня холодно.', 'Идёт дождь.', 'Какая погода?', 'Летом жарко.', 'Минус десять градусов.'],
  },
  {
    day: 15,
    theme: 'Body & health',
    grammarFocus: 'Dative with feel/hurt (мне больно)',
    words: [
      w('голова', 'head', 'У меня болит голова.', 'My head hurts.', 'Голова кружится.', 'I feel dizzy.'),
      w('рука', 'arm / hand', 'Подними руку.', 'Raise your hand.', 'Правая рука.', 'The right hand.'),
      w('нога', 'leg / foot', 'Нога болит.', 'My leg hurts.', 'Длинные ноги.', 'Long legs.'),
      w('глаз', 'eye', 'Голубые глаза.', 'Blue eyes.', 'Закрой глаза.', 'Close your eyes.'),
      w('зуб', 'tooth', 'Болит зуб.', 'My tooth hurts.', 'Чисти зубы.', 'Brush your teeth.'),
      w('боль', 'pain', 'Сильная боль.', 'Strong pain.', 'Где болит?', 'Where does it hurt?'),
      w('врач', 'doctor', 'Иду к врачу.', 'I am going to the doctor.', 'Врач помогает.', 'The doctor helps.'),
      w('лекарство', 'medicine', 'Принимай лекарство.', 'Take the medicine.', 'Лекарство помогает.', 'The medicine helps.'),
      w('здоровье', 'health', 'Здоровье важно.', 'Health is important.', 'Крепкое здоровье.', 'Strong health.'),
      w('аптека', 'pharmacy', 'Аптека на углу.', 'The pharmacy is on the corner.', 'Иду в аптеку.', 'I am going to the pharmacy.'),
    ],
    grammarPrompts: [
      { prompt: '___ больно. (to me)', options: ['Я', 'Мне', 'Меня', 'Мной'], correct: 1 },
      { prompt: '___ холодно. (to him)', options: ['Он', 'Ему', 'Его', 'Им'], correct: 1 },
      { prompt: '___ нужен врач. (to her)', options: ['Она', 'Ей', 'Её', 'Ею'], correct: 1 },
      { prompt: '___ плохо. (to us)', options: ['Мы', 'Нам', 'Нас', 'Нами'], correct: 1 },
      { prompt: 'Иду к ___. (doctor, dat)', options: ['врач', 'врачу', 'врача', 'врачом'], correct: 1 },
      { prompt: '___ нравится. (to me, pleases)', options: ['Я', 'Мне', 'Меня', 'Мной'], correct: 1 },
    ],
    speakingPrompts: ['У меня болит голова.', 'Мне плохо.', 'Иду к врачу.', 'Где аптека?', 'Принимай лекарство.'],
  },
];
