import type { RawDay } from './curriculum-data';
import { w } from './curriculum-data-helpers';

export const CURRICULUM_PART2: RawDay[] = [
  {
    day: 4,
    theme: 'Colors & descriptions',
    grammarFocus: 'Adjective agreement (nominative)',
    words: [
      w('красный', 'red', 'Красная машина стоит там.', 'The red car is parked there.', 'Я люблю красный цвет.', 'I love the color red.'),
      w('синий', 'blue', 'Синее небо сегодня.', 'The sky is blue today.', 'У него синие глаза.', 'He has blue eyes.'),
      w('зелёный', 'green', 'Зелёный парк рядом.', 'There is a green park nearby.', 'Зелёное яблоко на столе.', 'A green apple on the table.'),
      w('белый', 'white', 'Белый снег зимой.', 'White snow in winter.', 'Белая рубашка чистая.', 'The white shirt is clean.'),
      w('чёрный', 'black', 'Чёрная кошка на крыше.', 'A black cat on the roof.', 'Чёрный кофе без сахара.', 'Black coffee without sugar.'),
      w('большой', 'big', 'Большой дом на улице.', 'A big house on the street.', 'Москва — большой город.', 'Moscow is a big city.'),
      w('маленький', 'small', 'Маленький ребёнок спит.', 'A small child is sleeping.', 'Маленькая комната уютная.', 'The small room is cozy.'),
      w('красивый', 'beautiful', 'Красивый закат сегодня.', 'A beautiful sunset today.', 'Она красивая женщина.', 'She is a beautiful woman.'),
      w('новый', 'new', 'Новый телефон работает.', 'The new phone works.', 'Новая машина быстрая.', 'The new car is fast.'),
      w('старый', 'old', 'Старый дом в центре.', 'An old house in the center.', 'Старый друг приехал.', 'An old friend arrived.'),
    ],
    grammarPrompts: [
      { prompt: '___ книга (new, fem)', options: ['новый', 'новая', 'новое', 'новые'], correct: 1 },
      { prompt: '___ дом (big, masc)', options: ['большая', 'большое', 'большой', 'большие'], correct: 2 },
      { prompt: '___ окно (small, neut)', options: ['маленький', 'маленькая', 'маленькое', 'маленькие'], correct: 2 },
      { prompt: '___ машины (red, pl)', options: ['красный', 'красная', 'красное', 'красные'], correct: 3 },
      { prompt: '___ платье (beautiful, neut)', options: ['красивая', 'красивое', 'красивый', 'красивые'], correct: 1 },
      { prompt: '___ друг (old, masc)', options: ['старая', 'старое', 'старый', 'старые'], correct: 2 },
    ],
    speakingPrompts: ['Красная машина.', 'Синее небо.', 'Большой город.', 'Маленькая комната.', 'Красивый закат.'],
  },
  {
    day: 5,
    theme: 'Family & people',
    grammarFocus: 'Possessive pronouns',
    words: [
      w('мама', 'mom', 'Моя мама дома.', 'My mom is at home.', 'Мама готовит обед.', 'Mom is cooking lunch.'),
      w('папа', 'dad', 'Мой папа на работе.', 'My dad is at work.', 'Папа читает газету.', 'Dad is reading the newspaper.'),
      w('брат', 'brother', 'У меня один брат.', 'I have one brother.', 'Мой брат студент.', 'My brother is a student.'),
      w('сестра', 'sister', 'Моя сестра врач.', 'My sister is a doctor.', 'Сестра живёт в Питере.', 'My sister lives in St. Petersburg.'),
      w('сын', 'son', 'Их сын учится в школе.', 'Their son studies at school.', 'Мой сын пять лет.', 'My son is five years old.'),
      w('дочь', 'daughter', 'Наша дочь музыкант.', 'Our daughter is a musician.', 'Дочь поёт песню.', 'The daughter is singing a song.'),
      w('бабушка', 'grandmother', 'Бабушка живёт в деревне.', 'Grandma lives in the village.', 'Моя бабушка готовит борщ.', 'My grandma makes borscht.'),
      w('дедушка', 'grandfather', 'Дедушка рассказывает истории.', 'Grandpa tells stories.', 'Мой дедушка рыбак.', 'My grandpa is a fisherman.'),
      w('муж', 'husband', 'Её муж инженер.', 'Her husband is an engineer.', 'Мой муж дома.', 'My husband is at home.'),
      w('жена', 'wife', 'Его жена учитель.', 'His wife is a teacher.', 'Жена работает в больнице.', 'The wife works at the hospital.'),
    ],
    grammarPrompts: [
      { prompt: '___ друг (my, masc)', options: ['моя', 'моё', 'мой', 'мои'], correct: 2 },
      { prompt: '___ семья (my, fem)', options: ['мой', 'моя', 'моё', 'мои'], correct: 1 },
      { prompt: '___ дети (our, pl)', options: ['наш', 'наша', 'наше', 'наши'], correct: 3 },
      { prompt: '___ дом (their, masc)', options: ['их', 'его', 'её', 'наш'], correct: 0 },
      { prompt: '___ книга (her, fem)', options: ['его', 'её', 'их', 'твоя'], correct: 1 },
      { prompt: '___ имя (your, neut)', options: ['твой', 'твоя', 'твоё', 'твои'], correct: 2 },
    ],
    speakingPrompts: ['Моя мама дома.', 'У меня два брата.', 'Моя сестра врач.', 'Наша семья большая.', 'Его жена учитель.'],
  },
  {
    day: 6,
    theme: 'Animals',
    grammarFocus: 'Plural noun patterns',
    words: [
      w('собака', 'dog', 'Собака бегает в парке.', 'The dog runs in the park.', 'Большая собака лает.', 'The big dog barks.'),
      w('кошка', 'cat', 'Кошка спит на диване.', 'The cat sleeps on the sofa.', 'Чёрная кошка мяукает.', 'The black cat meows.'),
      w('птица', 'bird', 'Птица поёт утром.', 'The bird sings in the morning.', 'Маленькая птица летит.', 'A small bird flies.'),
      w('рыба', 'fish', 'Рыба плавает в воде.', 'The fish swims in the water.', 'Мы едим рыбу.', 'We eat fish.'),
      w('лошадь', 'horse', 'Лошадь бежит быстро.', 'The horse runs fast.', 'Белая лошадь красивая.', 'The white horse is beautiful.'),
      w('корова', 'cow', 'Корова даёт молоко.', 'The cow gives milk.', 'Коровы на ферме.', 'Cows are on the farm.'),
      w('медведь', 'bear', 'Медведь живёт в лесу.', 'The bear lives in the forest.', 'Большой медведь опасный.', 'A big bear is dangerous.'),
      w('волк', 'wolf', 'Волк охотится ночью.', 'The wolf hunts at night.', 'Серый волк в тайге.', 'A gray wolf in the taiga.'),
      w('заяц', 'hare / rabbit', 'Заяц прыгает по полю.', 'The hare jumps across the field.', 'Белый заяц зимой.', 'A white hare in winter.'),
      w('мышь', 'mouse', 'Мышь бежит под стол.', 'The mouse runs under the table.', 'Мыши в старом доме.', 'Mice in the old house.'),
    ],
    grammarPrompts: [
      { prompt: 'один стол → два ___', options: ['стол', 'стола', 'столы', 'столов'], correct: 1 },
      { prompt: 'одна кошка → три ___', options: ['кошка', 'кошки', 'кошек', 'кошку'], correct: 1 },
      { prompt: 'один друг → пять ___', options: ['друга', 'друг', 'друзей', 'друзья'], correct: 2 },
      { prompt: 'одна книга → много ___', options: ['книга', 'книги', 'книг', 'книгу'], correct: 2 },
      { prompt: 'один дом → несколько ___', options: ['дом', 'дома', 'домов', 'дому'], correct: 1 },
      { prompt: 'одна мышь → две ___', options: ['мышь', 'мыши', 'мышей', 'мышью'], correct: 1 },
    ],
    speakingPrompts: ['Собака в парке.', 'Кошка на диване.', 'Птица поёт.', 'Медведь в лесу.', 'Коровы на ферме.'],
  },
  {
    day: 7,
    theme: 'Food & drinks',
    grammarFocus: 'Accusative (direct object, eat/drink)',
    words: [
      w('хлеб', 'bread', 'Я ем хлеб с маслом.', 'I eat bread with butter.', 'Свежий хлеб вкусный.', 'Fresh bread is tasty.'),
      w('молоко', 'milk', 'Дети пьют молоко.', 'Children drink milk.', 'Я покупаю молоко.', 'I buy milk.'),
      w('вода', 'water', 'Мне нужна вода.', 'I need water.', 'Пью воду каждый день.', 'I drink water every day.'),
      w('кофе', 'coffee', 'Утром пью кофе.', 'I drink coffee in the morning.', 'Чёрный кофе без сахара.', 'Black coffee without sugar.'),
      w('чай', 'tea', 'Русские любят чай.', 'Russians love tea.', 'Зелёный чай полезный.', 'Green tea is healthy.'),
      w('сыр', 'cheese', 'Я ем сыр на завтрак.', 'I eat cheese for breakfast.', 'Русский сыр вкусный.', 'Russian cheese is tasty.'),
      w('мясо', 'meat', 'Он не ест мясо.', 'He does not eat meat.', 'Мясо на сковороде.', 'Meat in the pan.'),
      w('суп', 'soup', 'Бабушка варит суп.', 'Grandma cooks soup.', 'Горячий суп на столе.', 'Hot soup on the table.'),
      w('яблоко', 'apple', 'Я ем яблоко.', 'I eat an apple.', 'Красное яблоко сладкое.', 'The red apple is sweet.'),
      w('борщ', 'borscht', 'Борщ — русский суп.', 'Borscht is a Russian soup.', 'Я люблю борщ.', 'I love borscht.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ем ___ (хлеб)', options: ['хлеб', 'хлеба', 'хлебу', 'хлебом'], correct: 0 },
      { prompt: 'Я пью ___ (вода)', options: ['вода', 'воду', 'воды', 'воде'], correct: 1 },
      { prompt: 'Я покупаю ___ (сыр)', options: ['сыр', 'сыра', 'сыру', 'сыром'], correct: 0 },
      { prompt: 'Она ест ___ (яблоко)', options: ['яблоко', 'яблока', 'яблоку', 'яблоком'], correct: 0 },
      { prompt: 'Мы варим ___ (суп)', options: ['суп', 'супа', 'супу', 'супом'], correct: 0 },
      { prompt: 'Он пьёт ___ (чай)', options: ['чай', 'чая', 'чаю', 'чаем'], correct: 0 },
    ],
    speakingPrompts: ['Я ем хлеб.', 'Пью кофе утром.', 'Люблю борщ.', 'Купи молоко, пожалуйста.', 'Горячий чай.'],
  },
  {
    day: 8,
    theme: 'At the café / restaurant',
    grammarFocus: 'Polite requests (можно, хотеть)',
    words: [
      w('меню', 'menu', 'Можно меню, пожалуйста?', 'Can I have the menu, please?', 'Меню на столе.', 'The menu is on the table.'),
      w('официант', 'waiter', 'Официант приносит заказ.', 'The waiter brings the order.', 'Позовите официанта.', 'Call the waiter.'),
      w('счёт', 'bill / check', 'Счёт, пожалуйста.', 'The bill, please.', 'Счёт за столом.', 'The bill for the table.'),
      w('заказ', 'order', 'Я делаю заказ.', 'I am placing an order.', 'Заказ готов.', 'The order is ready.'),
      w('стол', 'table', 'Стол у окна свободен.', 'The table by the window is free.', 'Забронируйте стол.', 'Reserve a table.'),
      w('завтрак', 'breakfast', 'Завтрак с восьми.', 'Breakfast from eight.', 'Завтрак включён.', 'Breakfast is included.'),
      w('обед', 'lunch', 'Обед в два часа.', 'Lunch at two o\'clock.', 'Где пообедать?', 'Where to have lunch?'),
      w('ужин', 'dinner', 'Ужин в ресторане.', 'Dinner at the restaurant.', 'Ужин готов.', 'Dinner is ready.'),
      w('хочу', 'I want', 'Я хочу кофе.', 'I want coffee.', 'Что вы хотите?', 'What would you like?'),
      w('можно', 'may I / is it allowed', 'Можно сюда сесть?', 'May I sit here?', 'Можно ещё хлеба?', 'May I have more bread?'),
    ],
    grammarPrompts: [
      { prompt: '___ кофе, пожалуйста. (I want)', options: ['Хочу', 'Хочешь', 'Хочет', 'Хотим'], correct: 0 },
      { prompt: '___ меню? (May I)', options: ['Хочу', 'Можно', 'Надо', 'Нужно'], correct: 1 },
      { prompt: 'Что вы ___? (want)', options: ['хочу', 'хочешь', 'хотите', 'хотят'], correct: 2 },
      { prompt: 'Она ___ чай. (wants)', options: ['хочу', 'хочешь', 'хочет', 'хотим'], correct: 2 },
      { prompt: '___ счёт, пожалуйста.', options: ['Хочу', 'Можно', 'Дай', 'Буду'], correct: 1 },
      { prompt: 'Мы ___ обедать. (want to)', options: ['хочу', 'хотим', 'хотите', 'хотят'], correct: 1 },
    ],
    speakingPrompts: ['Меню, пожалуйста.', 'Счёт, пожалуйста.', 'Я хочу кофе.', 'Можно сюда сесть?', 'Стол у окна.'],
  },
  {
    day: 9,
    theme: 'Home & rooms',
    grammarFocus: 'Prepositional case (where?)',
    words: [
      w('дом', 'house / home', 'Я дома.', 'I am at home.', 'Большой дом в деревне.', 'A big house in the village.'),
      w('комната', 'room', 'Комната светлая.', 'The room is bright.', 'В комнате кровать.', 'There is a bed in the room.'),
      w('кухня', 'kitchen', 'На кухне готовят.', 'They cook in the kitchen.', 'Кухня маленькая.', 'The kitchen is small.'),
      w('спальня', 'bedroom', 'Спальня на втором этаже.', 'The bedroom is on the second floor.', 'В спальне тихо.', 'It is quiet in the bedroom.'),
      w('ванная', 'bathroom', 'Ванная комната чистая.', 'The bathroom is clean.', 'Где ванная?', 'Where is the bathroom?'),
      w('окно', 'window', 'Окно открыто.', 'The window is open.', 'У окна стол.', 'A table by the window.'),
      w('дверь', 'door', 'Дверь закрыта.', 'The door is closed.', 'Открой дверь.', 'Open the door.'),
      w('кровать', 'bed', 'Кровать у стены.', 'The bed is against the wall.', 'Удобная кровать.', 'A comfortable bed.'),
      w('диван', 'sofa', 'Диван в гостиной.', 'The sofa is in the living room.', 'Садись на диван.', 'Sit on the sofa.'),
      w('стена', 'wall', 'На стене картина.', 'There is a picture on the wall.', 'Белая стена.', 'A white wall.'),
    ],
    grammarPrompts: [
      { prompt: 'Я живу ___ Москве. (in)', options: ['Москва', 'Москве', 'Москву', 'Москвой'], correct: 1 },
      { prompt: 'Книга ___ столе. (on)', options: ['стол', 'стола', 'столе', 'столу'], correct: 2 },
      { prompt: 'Мы в ___ (kitchen, prep)', options: ['кухня', 'кухне', 'кухню', 'кухней'], correct: 1 },
      { prompt: 'Он ___ доме. (at home)', options: ['дом', 'дома', 'дому', 'домом'], correct: 1 },
      { prompt: 'Картина на ___. (wall, prep)', options: ['стена', 'стены', 'стене', 'стену'], correct: 2 },
      { prompt: 'Дети в ___. (room, prep)', options: ['комната', 'комнате', 'комнату', 'комнатой'], correct: 1 },
    ],
    speakingPrompts: ['Я дома.', 'Кухня маленькая.', 'Где ванная?', 'Окно открыто.', 'Диван в гостиной.'],
  },
  {
    day: 10,
    theme: 'City & places',
    grammarFocus: 'Prepositions в/на + prep case',
    words: [
      w('город', 'city', 'Москва — большой город.', 'Moscow is a big city.', 'В городе много людей.', 'There are many people in the city.'),
      w('улица', 'street', 'Улица широкая.', 'The street is wide.', 'На этой улице магазин.', 'There is a shop on this street.'),
      w('магазин', 'store', 'Магазин открыт.', 'The store is open.', 'Иду в магазин.', 'I am going to the store.'),
      w('больница', 'hospital', 'Больница рядом.', 'The hospital is nearby.', 'Он работает в больнице.', 'He works at the hospital.'),
      w('школа', 'school', 'Школа на углу.', 'The school is on the corner.', 'Дети в школе.', 'The children are at school.'),
      w('парк', 'park', 'В парке гуляют.', 'People walk in the park.', 'Красивый парк.', 'A beautiful park.'),
      w('музей', 'museum', 'Музей закрыт по понедельникам.', 'The museum is closed on Mondays.', 'Идём в музей.', 'Let\'s go to the museum.'),
      w('театр', 'theater', 'Театр в центре.', 'The theater is in the center.', 'Был в театре вчера.', 'I was at the theater yesterday.'),
      w('станция', 'station', 'Станция метро близко.', 'The metro station is close.', 'Жду на станции.', 'I am waiting at the station.'),
      w('площадь', 'square', 'Красная площадь в Москве.', 'Red Square is in Moscow.', 'На площади народ.', 'People on the square.'),
    ],
    grammarPrompts: [
      { prompt: 'Я в ___ (school, prep)', options: ['школа', 'школе', 'школу', 'школой'], correct: 1 },
      { prompt: 'Она на ___ (work, prep)', options: ['работа', 'работе', 'работу', 'работой'], correct: 1 },
      { prompt: 'Мы в ___ (park, prep)', options: ['парк', 'парке', 'парк', 'парком'], correct: 1 },
      { prompt: 'Книга на ___ (table, prep)', options: ['стол', 'стола', 'столе', 'столу'], correct: 2 },
      { prompt: 'Иду в ___ (museum, acc)', options: ['музей', 'музее', 'музея', 'музею'], correct: 0 },
      { prompt: 'Встреча на ___ (square, prep)', options: ['площадь', 'площади', 'площадью', 'площадью'], correct: 1 },
    ],
    speakingPrompts: ['Иду в магазин.', 'Школа на углу.', 'Парк красивый.', 'Станция метро близко.', 'На Красной площади.'],
  },
];
