import type { RawDay } from './curriculum-data';
import { w } from './curriculum-data-helpers';

export const CURRICULUM_PART5: RawDay[] = [
  {
    day: 21,
    theme: 'Technology & media',
    grammarFocus: 'Prefixed verbs intro',
    words: [
      w('компьютер', 'computer', 'Новый компьютер.', 'A new computer.', 'Работаю на компьютере.', 'I work on the computer.'),
      w('телефон', 'phone', 'Мой телефон.', 'My phone.', 'Звони по телефону.', 'Call on the phone.'),
      w('интернет', 'internet', 'Есть интернет?', 'Is there internet?', 'Без интернета.', 'Without internet.'),
      w('сайт', 'website', 'Посети сайт.', 'Visit the website.', 'Официальный сайт.', 'Official website.'),
      w('письмо', 'letter / email', 'Пишу письмо.', 'I am writing a letter.', 'Электронное письмо.', 'An email.'),
      w('новости', 'news', 'Смотрю новости.', 'I watch the news.', 'Хорошие новости.', 'Good news.'),
      w('фото', 'photo', 'Красивое фото.', 'A beautiful photo.', 'Сделай фото.', 'Take a photo.'),
      w('видео', 'video', 'Смотрю видео.', 'I watch a video.', 'Интересное видео.', 'An interesting video.'),
      w('включить', 'to turn on', 'Включи свет.', 'Turn on the light.', 'Включи телевизор.', 'Turn on the TV.'),
      w('выключить', 'to turn off', 'Выключи компьютер.', 'Turn off the computer.', 'Выключи телефон.', 'Turn off the phone.'),
    ],
    grammarPrompts: [
      { prompt: '___ телевизор. (turn on, imperf)', options: ['Включи', 'Включу', 'Включал', 'Включала'], correct: 0 },
      { prompt: 'Я ___ компьютер. (turn off, completed)', options: ['выключаю', 'выключу', 'выключил', 'выключала'], correct: 2 },
      { prompt: '___ письмо завтра. (write, future)', options: ['Пишу', 'Напишу', 'Писал', 'Написала'], correct: 1 },
      { prompt: '___ новости каждый день. (read/watch)', options: ['Прочитаю', 'Читаю', 'Прочитал', 'Прочитала'], correct: 1 },
      { prompt: '___ интернет. (connect)', options: ['Подключи', 'Подключу', 'Подключал', 'Подключала'], correct: 0 },
      { prompt: '___ фото вчера. (take, completed)', options: ['Делаю', 'Сделаю', 'Сделал', 'Делала'], correct: 2 },
    ],
    speakingPrompts: ['Есть интернет?', 'Включи свет.', 'Сделай фото.', 'Пишу письмо.', 'Смотрю новости.'],
  },
  {
    day: 22,
    theme: 'Emotions & personality',
    grammarFocus: 'Short-form adjectives',
    words: [
      w('счастье', 'happiness', 'Счастье важно.', 'Happiness is important.', 'Желаю счастья.', 'I wish you happiness.'),
      w('любовь', 'love', 'Любовь сильная.', 'Love is strong.', 'Любовь к семье.', 'Love for family.'),
      w('радость', 'joy', 'Большая радость.', 'Great joy.', 'Радость в глазах.', 'Joy in the eyes.'),
      w('грусть', 'sadness', 'Грусть проходит.', 'Sadness passes.', 'Без грусти.', 'Without sadness.'),
      w('страх', 'fear', 'Страх уходит.', 'Fear goes away.', 'Нет страха.', 'No fear.'),
      w('злой', 'angry', 'Он зол.', 'He is angry.', 'Не будь злым.', 'Don\'t be angry.'),
      w('добрый', 'kind', 'Она добрая.', 'She is kind.', 'Добрый человек.', 'A kind person.'),
      w('умный', 'smart', 'Он умный.', 'He is smart.', 'Умная девочка.', 'A smart girl.'),
      w('ленивый', 'lazy', 'Я ленив.', 'I am lazy.', 'Не будь ленивым.', 'Don\'t be lazy.'),
      w('смелый', 'brave', 'Она смела.', 'She is brave.', 'Смелый солдат.', 'A brave soldier.'),
    ],
    grammarPrompts: [
      { prompt: 'Он ___. (is tired, short masc)', options: ['устал', 'устала', 'устало', 'устали'], correct: 0 },
      { prompt: 'Она ___. (is glad, short fem)', options: ['рад', 'рада', 'радо', 'рады'], correct: 1 },
      { prompt: 'Мне ___. (is boring, short neut)', options: ['скучен', 'скучна', 'скучно', 'скучны'], correct: 2 },
      { prompt: 'Мы ___. (are ready, short pl)', options: ['готов', 'готова', 'готово', 'готовы'], correct: 3 },
      { prompt: 'Он ___. (is right, short masc)', options: ['прав', 'права', 'право', 'правы'], correct: 0 },
      { prompt: 'Дети ___. (are happy, short pl)', options: ['счастлив', 'счастлива', 'счастливо', 'счастливы'], correct: 3 },
    ],
    speakingPrompts: ['Я рад.', 'Она добрая.', 'Не будь злым.', 'Мне скучно.', 'Он умный.'],
  },
  {
    day: 23,
    theme: 'Travel & hotel',
    grammarFocus: 'Future tense (быть + infinitive)',
    words: [
      w('отель', 'hotel', 'Отель в центре.', 'The hotel is downtown.', 'Бронирую отель.', 'I book a hotel.'),
      w('номер', 'room (hotel)', 'Номер с видом.', 'Room with a view.', 'Свободный номер.', 'Available room.'),
      w('билет', 'ticket', 'Купи билет.', 'Buy a ticket.', 'Билет на поезд.', 'Train ticket.'),
      w('паспорт', 'passport', 'Мой паспорт.', 'My passport.', 'Покажите паспорт.', 'Show your passport.'),
      w('багаж', 'luggage', 'Мой багаж.', 'My luggage.', 'Где багаж?', 'Where is the luggage?'),
      w('турист', 'tourist', 'Я турист.', 'I am a tourist.', 'Много туристов.', 'Many tourists.'),
      w('экскурсия', 'excursion / tour', 'Экскурсия завтра.', 'The tour is tomorrow.', 'Интересная экскурсия.', 'An interesting tour.'),
      w('путешествие', 'journey / trip', 'Хорошее путешествие.', 'A good trip.', 'Люблю путешествия.', 'I love travel.'),
      w('приехать', 'to arrive (by transport)', 'Приеду завтра.', 'I will arrive tomorrow.', 'Когда приедешь?', 'When will you arrive?'),
      w('уехать', 'to leave (by transport)', 'Уеду в пятницу.', 'I will leave on Friday.', 'Пора уехать.', 'Time to leave.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ завтра. (will go)', options: ['иду', 'пойду', 'шёл', 'ходил'], correct: 1 },
      { prompt: 'Она ___ в Москву. (will arrive)', options: ['приезжает', 'приедет', 'приехала', 'приезжала'], correct: 1 },
      { prompt: 'Мы ___ отель. (will book)', options: ['бронируем', 'забронируем', 'бронировали', 'бронировала'], correct: 1 },
      { prompt: 'Он ___ вечером. (will leave)', options: ['уезжает', 'уедет', 'уехал', 'уезжал'], correct: 1 },
      { prompt: 'Я ___ билет. (will buy)', options: ['покупаю', 'куплю', 'покупал', 'покупала'], correct: 1 },
      { prompt: 'Они ___ через неделю. (will return)', options: ['возвращаются', 'вернутся', 'вернулись', 'возвращались'], correct: 1 },
    ],
    speakingPrompts: ['Бронирую отель.', 'Купи билет.', 'Приеду завтра.', 'Покажите паспорт.', 'Люблю путешествия.'],
  },
  {
    day: 24,
    theme: 'Phone & messaging',
    grammarFocus: 'Imperative mood',
    words: [
      w('звонок', 'call / ring', 'Телефонный звонок.', 'Phone call.', 'Жду звонка.', 'Waiting for a call.'),
      w('сообщение', 'message', 'Новое сообщение.', 'New message.', 'Отправь сообщение.', 'Send a message.'),
      w('номер', 'number', 'Какой номер?', 'What number?', 'Номер телефона.', 'Phone number.'),
      w('ответить', 'to answer / reply', 'Ответь на звонок.', 'Answer the call.', 'Ответь, пожалуйста.', 'Reply, please.'),
      w('позвонить', 'to call', 'Позвони мне.', 'Call me.', 'Я позвоню.', 'I will call.'),
      w('отправить', 'to send', 'Отправь фото.', 'Send the photo.', 'Отправлю завтра.', 'I will send tomorrow.'),
      w('получить', 'to receive', 'Получил сообщение.', 'I received a message.', 'Получишь завтра.', 'You will receive tomorrow.'),
      w('ждать', 'to wait', 'Жду ответа.', 'Waiting for an answer.', 'Подожди минуту.', 'Wait a minute.'),
      w('слышать', 'to hear', 'Ты меня слышишь?', 'Can you hear me?', 'Плохо слышно.', 'Hard to hear.'),
      w('говорить', 'to speak / talk', 'Говори громче.', 'Speak louder.', 'О чём говорим?', 'What are we talking about?'),
    ],
    grammarPrompts: [
      { prompt: '___ мне! (call me, imper)', options: ['Звони', 'Позвони', 'Звонил', 'Звонила'], correct: 1 },
      { prompt: '___ тихо! (speak, imper)', options: ['Говори', 'Скажи', 'Говорил', 'Говорила'], correct: 0 },
      { prompt: '___ сообщение! (send, imper)', options: ['Отправляй', 'Отправь', 'Отправлял', 'Отправляла'], correct: 1 },
      { prompt: '___ здесь! (wait, imper)', options: ['Жди', 'Подожди', 'Ждал', 'Ждала'], correct: 1 },
      { prompt: 'Не ___! (don\'t worry, imper)', options: ['волнуйся', 'волнуй', 'волновался', 'волновалась'], correct: 0 },
      { prompt: '___ на вопрос! (answer, imper)', options: ['Отвечай', 'Ответь', 'Отвечал', 'Отвечала'], correct: 1 },
    ],
    speakingPrompts: ['Позвони мне.', 'Ты меня слышишь?', 'Отправь сообщение.', 'Говори громче.', 'Подожди минуту.'],
  },
  {
    day: 25,
    theme: 'Household chores',
    grammarFocus: 'Reflexive verbs (-ся)',
    words: [
      w('уборка', 'cleaning', 'Делаю уборку.', 'I am cleaning.', 'Генеральная уборка.', 'Deep cleaning.'),
      w('стирка', 'laundry', 'Стирка готова.', 'Laundry is done.', 'Машина для стирки.', 'Washing machine.'),
      w('готовить', 'to cook / prepare', 'Готовлю обед.', 'I am cooking lunch.', 'Люблю готовить.', 'I like to cook.'),
      w('мыть', 'to wash', 'Мою посуду.', 'I wash the dishes.', 'Мой руки.', 'Wash your hands.'),
      w('убирать', 'to clean / tidy', 'Убираю комнату.', 'I clean the room.', 'Надо убрать.', 'Need to tidy up.'),
      w('стирать', 'to do laundry', 'Стираю бельё.', 'I do the laundry.', 'Стираю каждую неделю.', 'I do laundry every week.'),
      w('гладить', 'to iron', 'Глажу рубашку.', 'I iron the shirt.', 'Ненавижу гладить.', 'I hate ironing.'),
      w('пылесос', 'vacuum cleaner', 'Включи пылесос.', 'Turn on the vacuum.', 'Новый пылесос.', 'New vacuum cleaner.'),
      w('мусор', 'trash / garbage', 'Вынеси мусор.', 'Take out the trash.', 'Мусорное ведро.', 'Trash bin.'),
      w('просыпаться', 'to wake up', 'Просыпаюсь в семь.', 'I wake up at seven.', 'Трудно просыпаться.', 'Hard to wake up.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ каждый день. (wash myself)', options: ['мою', 'моюсь', 'мыл', 'мыла'], correct: 1 },
      { prompt: 'Она ___ утром. (gets dressed)', options: ['одевает', 'одевается', 'одевала', 'одевал'], correct: 1 },
      { prompt: 'Мы ___ в шесть. (wake up)', options: ['просыпаем', 'просыпаемся', 'просыпали', 'просыпалась'], correct: 1 },
      { prompt: 'Он ___ дома. (stays)', options: ['остаёт', 'остаётся', 'оставал', 'оставалась'], correct: 1 },
      { prompt: 'Дети ___ рано. (go to bed)', options: ['ложат', 'ложатся', 'ложили', 'ложилась'], correct: 1 },
      { prompt: 'Она ___ в зеркало. (looks)', options: ['смотрит', 'смотрится', 'смотрела', 'смотрел'], correct: 1 },
    ],
    speakingPrompts: ['Делаю уборку.', 'Вынеси мусор.', 'Готовлю обед.', 'Просыпаюсь в семь.', 'Мою посуду.'],
  },
  {
    day: 26,
    theme: 'Comparisons & opinions',
    grammarFocus: 'Comparative adjectives',
    words: [
      w('лучше', 'better', 'Это лучше.', 'This is better.', 'Завтра будет лучше.', 'Tomorrow will be better.'),
      w('хуже', 'worse', 'Сегодня хуже.', 'Today is worse.', 'Не хуже.', 'Not worse.'),
      w('больше', 'more / bigger', 'Больше времени.', 'More time.', 'Нужно больше.', 'Need more.'),
      w('меньше', 'less / smaller', 'Меньше сахара.', 'Less sugar.', 'Меньше проблем.', 'Fewer problems.'),
      w('дороже', 'more expensive', 'Это дороже.', 'This is more expensive.', 'Дороже, чем вчера.', 'More expensive than yesterday.'),
      w('дешевле', 'cheaper', 'Здесь дешевле.', 'It is cheaper here.', 'Намного дешевле.', 'Much cheaper.'),
      w('мнение', 'opinion', 'Моё мнение.', 'My opinion.', 'Какое твоё мнение?', 'What is your opinion?'),
      w('думаю', 'I think', 'Думаю, да.', 'I think so.', 'Что ты думаешь?', 'What do you think?'),
      w('согласен', 'I agree (masc)', 'Я согласен.', 'I agree.', 'Полностью согласен.', 'I completely agree.'),
      w('кажется', 'it seems', 'Мне кажется.', 'It seems to me.', 'Кажется, дождь.', 'It seems like rain.'),
    ],
    grammarPrompts: [
      { prompt: 'Москва ___ Питера. (bigger)', options: ['большой', 'больше', 'большая', 'большие'], correct: 1 },
      { prompt: 'Сегодня ___ вчера. (warmer)', options: ['теплее', 'тёплый', 'тёплая', 'тепло'], correct: 0 },
      { prompt: 'Этот дом ___. (taller)', options: ['высокий', 'выше', 'высокая', 'высоко'], correct: 1 },
      { prompt: 'Она ___ меня. (smarter)', options: ['умнее', 'умная', 'умный', 'умно'], correct: 0 },
      { prompt: 'Здесь ___. (cheaper)', options: ['дёшево', 'дешевле', 'дёшевый', 'дешёвая'], correct: 1 },
      { prompt: 'Это ___ того. (better than)', options: ['лучше', 'хороший', 'хорошо', 'лучший'], correct: 0 },
    ],
    speakingPrompts: ['Я согласен.', 'Мне кажется.', 'Это лучше.', 'Здесь дешевле.', 'Что ты думаешь?'],
  },
  {
    day: 27,
    theme: 'Past events & stories',
    grammarFocus: 'Past tense (verbs)',
    words: [
      w('вчера', 'yesterday', 'Вчера был дождь.', 'It rained yesterday.', 'Вчера работал.', 'I worked yesterday.'),
      w('рассказ', 'story / tale', 'Интересный рассказ.', 'An interesting story.', 'Расскажи рассказ.', 'Tell a story.'),
      w('помнить', 'to remember', 'Помню всё.', 'I remember everything.', 'Не помню.', 'I don\'t remember.'),
      w('забыть', 'to forget', 'Забыл ключи.', 'I forgot the keys.', 'Не забудь.', 'Don\'t forget.'),
      w('случиться', 'to happen', 'Что случилось?', 'What happened?', 'Это случилось вчера.', 'It happened yesterday.'),
      w('встретить', 'to meet', 'Встретил друга.', 'I met a friend.', 'Приятно встретить.', 'Nice to meet.'),
      w('сказать', 'to say / tell', 'Сказал правду.', 'He told the truth.', 'Что ты сказал?', 'What did you say?'),
      w('услышать', 'to hear (completed)', 'Услышал новость.', 'I heard the news.', 'Услышал шум.', 'I heard a noise.'),
      w('увидеть', 'to see (completed)', 'Увидел море.', 'I saw the sea.', 'Рад увидеть.', 'Glad to see.'),
      w('понять', 'to understand', 'Понял урок.', 'I understood the lesson.', 'Теперь понимаю.', 'Now I understand.'),
    ],
    grammarPrompts: [
      { prompt: 'Вчера я ___ домой. (went, masc)', options: ['иду', 'шёл', 'пойду', 'хожу'], correct: 1 },
      { prompt: 'Она ___ книгу. (read, fem)', options: ['читает', 'читала', 'прочитает', 'читала'], correct: 1 },
      { prompt: 'Мы ___ фильм. (watched)', options: ['смотрим', 'смотрели', 'посмотрим', 'смотрели'], correct: 1 },
      { prompt: 'Он ___ письмо. (wrote, masc)', options: ['пишет', 'писал', 'напишет', 'написал'], correct: 3 },
      { prompt: 'Они ___ вчера. (arrived)', options: ['приезжают', 'приехали', 'приедут', 'приезжали'], correct: 1 },
      { prompt: 'Я ___ другa. (met, masc)', options: ['встречаю', 'встретил', 'встречу', 'встречал'], correct: 1 },
    ],
    speakingPrompts: ['Что случилось?', 'Вчера работал.', 'Понял урок.', 'Расскажи историю.', 'Не забудь.'],
  },
  {
    day: 28,
    theme: 'Conditional & wishes',
    grammarFocus: 'бы + past/conditional mood lite',
    words: [
      w('если', 'if', 'Если будет время.', 'If there is time.', 'Если хочешь.', 'If you want.'),
      w('хотел бы', 'would like (masc)', 'Я хотел бы кофе.', 'I would like coffee.', 'Хотел бы помочь.', 'Would like to help.'),
      w('мог бы', 'could (masc)', 'Мог бы помочь.', 'Could help.', 'Не мог бы ты?', 'Could you?'),
      w('мечта', 'dream', 'Моя мечта.', 'My dream.', 'Мечта сбылась.', 'The dream came true.'),
      w('надежда', 'hope', 'Есть надежда.', 'There is hope.', 'Не теряй надежду.', 'Don\'t lose hope.'),
      w('желание', 'wish / desire', 'Моё желание.', 'My wish.', 'Исполнение желания.', 'Wish fulfillment.'),
      w('надеяться', 'to hope', 'Надеюсь на лучшее.', 'I hope for the best.', 'Надеюсь, да.', 'I hope so.'),
      w('мечтать', 'to dream', 'Мечтаю о море.', 'I dream of the sea.', 'Не переставай мечтать.', 'Don\'t stop dreaming.'),
      w('пожелать', 'to wish', 'Желаю успеха.', 'I wish you success.', 'Что пожелаешь?', 'What do you wish?'),
      w('бы', 'would / conditional particle', 'Я бы поехал.', 'I would go.', 'Как бы не опоздать.', 'Hope I am not late.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ поехал. (would go, masc)', options: ['бы', 'был', 'буду', 'б'], correct: 0 },
      { prompt: 'Она ___ помогла. (would help, fem)', options: ['бы', 'была', 'будет', 'б'], correct: 0 },
      { prompt: '___ у меня было время... (if I had)', options: ['Если', 'Когда', 'Хотя', 'Пока'], correct: 0 },
      { prompt: 'Я ___ хотел кофе. (would like)', options: ['бы', 'был', 'буду', 'есть'], correct: 0 },
      { prompt: '___ ты мне позвонил! (if only you called)', options: ['Если', 'Если бы', 'Когда', 'Хотя'], correct: 1 },
      { prompt: '___ не опоздать! (would that I not be late)', options: ['Бы', 'Б', 'Буду', 'Был'], correct: 0 },
    ],
    speakingPrompts: ['Я хотел бы кофе.', 'Если будет время.', 'Надеюсь на лучшее.', 'Мечтаю о море.', 'Желаю успеха.'],
  },
  {
    day: 29,
    theme: 'Idioms & colloquialisms',
    grammarFocus: 'Fixed expressions',
    words: [
      w('ничего себе', 'wow / no way', 'Ничего себе!', 'Wow!', 'Ничего себе новость.', 'What news!'),
      w('ладно', 'okay / fine', 'Ладно, договорились.', 'Okay, agreed.', 'Ладно, иду.', 'Okay, I am going.'),
      w('точно', 'exactly / for sure', 'Точно!', 'Exactly!', 'Точно знаю.', 'I know for sure.'),
      w('конечно', 'of course', 'Конечно!', 'Of course!', 'Конечно, помогу.', 'Of course, I will help.'),
      w('наверное', 'probably', 'Наверное, да.', 'Probably yes.', 'Наверное, опоздаю.', 'I will probably be late.'),
      w('кстати', 'by the way', 'Кстати, как дела?', 'By the way, how are you?', 'Кстати, забыл сказать.', 'By the way, I forgot to say.'),
      w('вообще', 'generally / at all', 'Вообще не знаю.', 'I don\'t know at all.', 'Вообще-то да.', 'Actually yes.'),
      w('ещё бы', 'you bet / sure would', 'Ещё бы!', 'You bet!', 'Ещё бы не рад.', 'Of course I would be glad.'),
      w('не за что', 'don\'t mention it', 'Спасибо! — Не за что.', 'Thanks! — Don\'t mention it.', 'Не за что.', 'You\'re welcome.'),
      w('давай', 'come on / let\'s', 'Давай идём!', 'Come on, let\'s go!', 'Давай, попробуй.', 'Come on, try.'),
    ],
    grammarPrompts: [
      { prompt: '"___" = of course', options: ['Ладно', 'Конечно', 'Наверное', 'Кстати'], correct: 1 },
      { prompt: '"___" = by the way', options: ['Вообще', 'Кстати', 'Точно', 'Давай'], correct: 1 },
      { prompt: '"___" = wow', options: ['Ладно', 'Ничего себе', 'Не за что', 'Ещё бы'], correct: 1 },
      { prompt: '"___" = probably', options: ['Точно', 'Наверное', 'Конечно', 'Давай'], correct: 1 },
      { prompt: '"___" = let\'s go', options: ['Ладно', 'Давай', 'Кстати', 'Вообще'], correct: 1 },
      { prompt: '"Не ___" = you\'re welcome', options: ['за что', 'за это', 'за меня', 'за нас'], correct: 0 },
    ],
    speakingPrompts: ['Ничего себе!', 'Конечно, помогу.', 'Кстати, как дела?', 'Давай идём!', 'Ладно, договорились.'],
  },
  {
    day: 30,
    theme: 'Review marathon',
    grammarFocus: 'Mixed interleaved everything',
    words: [
      w('язык', 'language', 'Русский язык сложный.', 'Russian is a complex language.', 'Изучаю язык.', 'I study the language.'),
      w('слово', 'word', 'Новое слово.', 'A new word.', 'Запомни слово.', 'Remember the word.'),
      w('фраза', 'phrase', 'Полезная фраза.', 'A useful phrase.', 'Повтори фразу.', 'Repeat the phrase.'),
      w('урок', 'lesson', 'Урок интересный.', 'The lesson is interesting.', 'Урок закончен.', 'The lesson is finished.'),
      w('практика', 'practice', 'Нужна практика.', 'Practice is needed.', 'Практика каждый день.', 'Practice every day.'),
      w('прогресс', 'progress', 'Есть прогресс.', 'There is progress.', 'Хороший прогресс.', 'Good progress.'),
      w('повторить', 'to repeat / review', 'Повтори слова.', 'Review the words.', 'Надо повторить.', 'Need to review.'),
      w('запомнить', 'to memorize', 'Запомни это.', 'Remember this.', 'Трудно запомнить.', 'Hard to memorize.'),
      w('понимать', 'to understand', 'Понимаю русский.', 'I understand Russian.', 'Теперь понимаю.', 'Now I understand.'),
      w('говорить', 'to speak', 'Говорю по-русски.', 'I speak Russian.', 'Хочу говорить лучше.', 'I want to speak better.'),
    ],
    grammarPrompts: [
      { prompt: 'Я ___ русский. (study)', options: ['изучаю', 'изучил', 'изучу', 'изучала'], correct: 0 },
      { prompt: 'Нужно ___. (practice)', options: ['практика', 'практиковать', 'практиковал', 'практиковала'], correct: 1 },
      { prompt: '___ слова каждый день. (review, imper)', options: ['Повторяй', 'Повтори', 'Повторил', 'Повторила'], correct: 0 },
      { prompt: 'Есть ___. (progress)', options: ['прогресс', 'прогресса', 'прогрессу', 'прогрессом'], correct: 0 },
      { prompt: 'Я ___ по-русски. (speak)', options: ['говорю', 'сказал', 'скажу', 'говорил'], correct: 0 },
      { prompt: 'Трудно ___. (memorize)', options: ['запомнить', 'запоминаю', 'запомнил', 'запомнила'], correct: 0 },
    ],
    speakingPrompts: [
      'Я изучаю русский язык.',
      'Практика каждый день.',
      'Есть прогресс.',
      'Говорю по-русски.',
      'Повтори фразу.',
    ],
  },
];
